### ISSUE TITLE
入口index.js报Cannot find module 'node:os'错误

### ISSUE THREAD

**Issue by luotianwens** [parvardegr/sharing#15]
这种写法是不是有兼容问题？node版本12.15.0，系统windows11，cpu：arm
![image](https://user-images.githubusercontent.com/42161323/194732871-99b9baa9-01f2-4821-b1ca-8aca60a69fb2.png)

**Comment by Seven-Y-Q-Guo** [comment]
> 这种写法是不是有兼容问题？node版本12.15.0，系统windows11，cpu：arm
> ![image](https://user-images.githubusercontent.com/42161323/194732871-99b9baa9-01f2-4821-b1ca-8aca60a69fb2.png)
> 

Please check the README which mentions it needs 16.x or later as node version.

**Comment by Seven-Y-Q-Guo** [comment]
#5 duplicate
