### ISSUE TITLE
Chinese and unicode are not supported

### ISSUE THREAD

**Issue by monk233** [parvardegr/sharing#17]
When the path contains Chinese or αβγ The QR code URL is garbled
![image](https://user-images.githubusercontent.com/52564907/194735131-b491dc6d-cdcd-48c4-bd99-aa791575bf55.png)

**Comment by Seven-Y-Q-Guo** [comment]
https://github.com/gtanner/qrcode-terminal/issues/39
The qrcode-terminal which we used to output the QR Code on terminal still have this issue.
