### ISSUE TITLE
[feature] support https and a basic password

### ISSUE THREAD

**Issue by huyz** [parvardegr/sharing#19]
It would be nice to avoid snooping, especially on public wi-fi.\

A self-signed certificate would be just fine

**Comment by Seven-Y-Q-Guo** [comment]
Hi huyz,

Many thanks for suggesting on this, the security is always important for us.
As you see I enable the https within this PR(https://github.com/parvardegr/sharing/pull/21), after checking the documentation of serve-handler which has been used in sharing as core module to serve static resources, the functionality for auth is still not implemented yet.

https://github.com/vercel/serve-handler/pull/96
https://github.com/vercel/serve-handler/issues/60

I would like to add it later once serve-handler done the job.

**Comment by parvardegr** [comment]
Hi @huyz,
Thanks for the suggestion, now we support basic authentication for share and receive.
also #21 will be merge soon.
