### ISSUE TITLE
y my QR code look like this？

### ISSUE THREAD

**Issue by CN-Jiang-tao** [parvardegr/sharing#20]
![微信截图_20221009161634](https://user-images.githubusercontent.com/85598102/194746139-6bb9601c-31c2-4782-bd4e-3401c5630d17.png)

**Comment by colgin** [comment]
maybe you should try powershell?

**Comment by CN-Jiang-tao** [comment]
![微信截图_20221010084705](https://user-images.githubusercontent.com/85598102/194787162-1d9242bc-1d9d-41af-aee8-206d376f5f9f.png)
still not work :(

**Comment by Seven-Y-Q-Guo** [comment]
> ![微信截图_20221010084705](https://user-images.githubusercontent.com/85598102/194787162-1d9242bc-1d9d-41af-aee8-206d376f5f9f.png) still not work :(

Please clone this repo and install the dependencies, then run
```bash
node bin/index.js 'your path for file or directory' -w
```

**Comment by CN-Jiang-tao** [comment]
![image](https://user-images.githubusercontent.com/85598102/194981085-d32d5562-d0af-40db-a0fa-4a1c9f6297d3.png)
ERROR when I run index.js

**Comment by Seven-Y-Q-Guo** [comment]
> ![image](https://user-images.githubusercontent.com/85598102/194981085-d32d5562-d0af-40db-a0fa-4a1c9f6297d3.png)
> ERROR when I run index.js

I don't think you have installed the dependence firstly, as it's mode for dev only.
btw, you can just update the package and try once again.
