### ISSUE TITLE
Nunjucks

### ISSUE THREAD

**Issue by LeoUpperThrower4** [parvardegr/sharing#28]
What do you think if we added Nunjucks template engine to the app?
I believe it would help display information on the screen, since we will not depend on the browser's way of showing folders/files. I did an implementation in my fork. Take a look! 
P.S: commits after Oct 7 are not there yet, but if you find it useful I will rebase and create a PR

**Comment by parvardegr** [comment]
Hi @LeoUpperThrower4 
Thanks a lot for mention this cool template engine, but as you can see we use a small amount of html and i think it’s better to keep it as simple as it is.

@Seven-Y-Q-Guo what do you think about it?

great regards

**Comment by Seven-Y-Q-Guo** [comment]
> Hi @LeoUpperThrower4 
> Thanks a lot for mention this cool template engine, but as you can see we use a small amount of html and i think it’s better to keep it as simple as it is.
> 
> @Seven-Y-Q-Guo what do you think about it?
> 
> great regards

I'm with you, as the core functionality is on terminal, if one day we want more on screen, then we could take a try.
