### ISSUE TITLE
Getting undefined for port when using receive

### ISSUE THREAD

**Issue by raimonomiar** [parvardegr/sharing#31]
![image](https://user-images.githubusercontent.com/20229326/195284728-858cc41f-5dbd-4229-874d-11e743af0aac.png)

**Comment by parvardegr** [comment]
Hi @raimonomiar 
which version you’re using? 
it should works fine in v1.2.2

by the way a temporary fix is specify a port for receiving use -q option

cheers

**Comment by raimonomiar** [comment]
@parvardegr the problem is only for the message that shows undefined.
The QR code works fine and made a pr for the fix https://github.com/parvardegr/sharing/pull/32

**Comment by parvardegr** [comment]
> @parvardegr the problem is only for the message that shows undefined. The QR code works fine and made a pr for the fix #32

you can just remove that console.log line, it wasn't suppose to be there, just a silly bug.

**Comment by parvardegr** [comment]
merged
