### ISSUE TITLE
QR code as text

### ISSUE THREAD

**Issue by jagondol** [parvardegr/sharing#37]
Is it correct that my phone recognize de QR code as a text instead of a link?
Probably need a config.qrcode addition in index.js?

**Comment by parvardegr** [comment]
@jagondol sorry for the late,
it seems there is no config for this purpose and it should works fine this way without any extra configuration.
could you send a screenshot of the output

**Comment by parvardegr** [comment]
since no one argue about this issue anymore i will close it
