### ISSUE TITLE
Run without sudo

### ISSUE THREAD

**Issue by mfyz** [parvardegr/sharing#4]
Why sharing requires root permission? At least better explanation needed.

**Comment by parvardegr** [comment]
hi @mfyz
does your current user have the right permissions to access the directory or the file that you want to share?

great regards

**Comment by mfyz** [comment]
Yep. I actually tried running
`sharing ./` in my home directory that didn't work. Then made it full absolute path, didn't work either (or asked sudo again).

Trying same with sudo, I got error #5

**Comment by parvardegr** [comment]
> Yep. I actually tried running `sharing ./` in my home directory that didn't work. Then made it full absolute path, didn't work either (or asked sudo again).
> 
> Trying same with sudo, I got error #5

can you try with node version 16.x? 
|# sharing ~

i will investigate this problem soon.
🙏

**Comment by adrianogil** [comment]
@mfyz I got the same error, but after some time I realized that what was calling was some sort of [built-in macOS binary](https://ss64.com/osx/sharing.html) from `/usr/sbin/sharing`. Try to call directly the binary from the global node_modules path.

**Comment by parvardegr** [comment]
> @mfyz I got the same error, but after some time I realized that what was calling was some sort of [built-in macOS binary](https://ss64.com/osx/sharing.html) from `/usr/sbin/sharing`. Try to call directly the binary from the global node_modules path.

@adrianogil thanks for the workaround 🙏

@mfyz in this case i will close this issue.
