### ISSUE TITLE
Why generate the QR-code that cannot be scanned

### ISSUE THREAD

**Issue by JGPeng** [parvardegr/sharing#46]
![image](https://user-images.githubusercontent.com/54806048/224591249-430b5631-5488-4dea-976e-eb1e73b09bff.png)

**Comment by colgin** [comment]
Hi, JGPeng, feel free to providing more info such as system info or bash info

**Comment by parvardegr** [comment]
@JGPeng 
Hi, you need to use -w
`sharing -w ./yourfile`
