### ISSUE TITLE
node:os package missing.

### ISSUE THREAD

**Issue by mfyz** [parvardegr/sharing#5]
Getting node:os package missing. Tried adding this package globally "node:os" don't work. I've added "os" and still getting same error:

![Screenshot 2022-10-06 09 34 11](https://user-images.githubusercontent.com/3248794/194326915-bb2cce52-ae71-41cc-bfe6-44bd9681771a.jpg)

Ideally, all dependencies should be installed with original npm install command (isn't that the point?).

**Comment by parvardegr** [comment]
hi @mfyz 
I’ll check this tomorrow, thanks for the report

**Comment by parvardegr** [comment]
Hi again @mfyz 
you need to use node version v16.x, i will mention it in the README.md

great regards
